# SPDX-FileCopyrightText: 2022 Alec Delaney
#
# SPDX-License-Identifier: MIT

on:
  release:
    types: [published]

jobs:
  upload-mpy-zips:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run MPY Action
      uses: adafruit/build-mpy@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        circuitpy-tag: "8.0.0-beta.0"
        mpy-directory: "microcontroller"
        mpy-manifest-file: "mpy_manifest.txt"
        mpy-manifest-type: "exclude"
        zip-directory: "microcontroller"
        zip-manifest-file: "zip_manifest.txt"
        zip-manifest-type: "exclude"
